version: "3"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  express:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
