name: Deploy netspeedtest to EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy docker-compose file with scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: 'docker-compose.yml'
          target: '/home/ec2-user/'

      - name: Copy scripts directory with scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: 'scripts'
          target: '/home/ec2-user/'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export MONGO_URI=${{ secrets.MONGO_URI }}
            export CLIENT_IP=${{ secrets.CLIENT_IP }}
            export GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
            export GCS_BUCKET=${{ secrets.GCS_BUCKET }}
            export GCP_SA_KEY=${{ secrets.GCP_SA_KEY }}
            export DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            export BACKUP_FILE=${{ secrets.BACKUP_FILE }}
            cd /home/ec2-user
            docker-compose up -d
            # Install gsutil
            curl https://sdk.cloud.google.com | bash
            source /root/google-cloud-sdk/path.bash.inc
            # Auth with GCP
            echo $GCP_SA_KEY > sa_key.json
            gcloud auth activate-service-account --key-file sa_key.json
            gcloud config set project $GCP_PROJECT_ID
            # Download backup file from GCS
            gsutil cp gs://$GCS_BUCKET/$BACKUP_FILE .
            # Restore MongoDB from backup
            mongorestore --uri $MONGO_URI --nsInclude "$DATABASE_NAME.*" --gzip --archive=$BACKUP_FILE
