name: Deploy netspeedtest to EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy docker-compose file with scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: 'docker-compose.yml'
          target: '/home/ec2-user/'

      - name: Copy scripts directory with scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: 'scripts'
          target: '/home/ec2-user/'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export MONGO_URI=${{ secrets.MONGO_URI }}
            export CLIENT_IP=${{ secrets.CLIENT_IP }}
            cd /home/ec2-user
